### ISSUE TITLE
[Feature] centos不在维护了，ubuntu会不会支持

### ISSUE THREAD

**Issue by snamper** [samwafgo/SamWaf#10]
### 产品版本

os

### 版本类型

- [ ] 社区版

### ⭐️ 需求描述

[Feature] centos不在维护了，ubuntu会不会支持

**Comment by samwafgo** [comment]
感谢关注。
支持的 请查看：https://github.com/samwafgo/SamWaf/blob/main/docs/Tested_supported_systems.md
