### ISSUE TITLE
[Bug] https配置不生效

### ISSUE THREAD

**Issue by xieyuhua** [samwafgo/SamWaf#11]
### 产品版本

20241011(v1.3.6)

### 版本类型

- [ ] 社区版

### 环境信息

宝塔 nginx 站点端口 http 80 , https 444
图片配置不生效，是什么原因呢

### 🐛 缺陷描述

![1728952980455](https://github.com/user-attachments/assets/f3db77a3-decd-44bd-b836-cfa4c6ca7cbd)

**Comment by samwafgo** [comment]
SamWaf这边如果是443 ，而且配置证书，  后端的端口改成80

**Comment by xieyuhua** [comment]
我打错了，宝塔的nginx 的配置80端口改成81，443改成了444，然后后台配置https时候端口配置443，后端端口改成的444、81，请求不得行

**Comment by samwafgo** [comment]
> 我打错了，宝塔的nginx 的配置80端口改成81，443改成了444，然后后台配置https时候端口配置443，后端端口改成的444、81，请求不得行

SamWaf配置443和80，后端端口都配置成81就行

**Comment by xieyuhua** [comment]
![image](https://github.com/user-attachments/assets/9990af8a-fd50-4fc9-bef9-e07f065a2b91)

[root@VM-16-5-centos go]# netstat -aonlp | grep 443
tcp6       0      0 :::443                  :::*                    LISTEN      3271/SamWafLinux64   off (0.00/0/0)

**Comment by xieyuhua** [comment]
![image](https://github.com/user-attachments/assets/d474e33d-10d6-4d66-9a97-970a702eda93)

选了证书之后，这个样配置不行

**Comment by samwafgo** [comment]
看下 ：系统设置->运行参数->当前web端口使用列表 
 这里面是什么了

**Comment by xieyuhua** [comment]
谢谢，可以了，是443被另外一个SamWaf占用，没有杀干净
