### ISSUE TITLE
[Feature] 建议拦截的IP可以输出到logs里面文件

### ISSUE THREAD

**Issue by opcache** [samwafgo/SamWaf#12]
### 产品版本

v1.3.6

### 版本类型

- [X] 社区版

### ⭐️ 需求描述

建议拦截的IP可以输出到logs里面文件，这个的场景，主要是考虑到可以把这些IP传递给其他工具或系统，比如拦截的IP写个脚本自动加入到iptables，或者写个工具PUSH到阿里云安全组里面，来拒绝掉这些IP的访问

**Comment by samwafgo** [comment]
感谢反馈，后面版本会支持，已经在排期了
