### ISSUE TITLE
[Bug] 不能启动

### ISSUE THREAD

**Issue by tqangxl** [samwafgo/SamWaf#2]
### 产品版本

最新版

### 版本类型

- [ ] 社区版

### 环境信息

win10 ENT LTSC

### 🐛 缺陷描述

{"level":"info","ts":"2024-09-21T10:34:47.519+0800","msg":"main server under service manager","pid":"5836","info":null}
{"level":"info","ts":"2024-09-21T10:34:47.614+0800","msg":"服务启动形式-----Start","pid":"5836","info":null}
{"level":"info","ts":"2024-09-21T10:34:47.615+0800","msg":"load config","pid":"5836","info":null}
{"level":"info","ts":"2024-09-21T10:34:47.615+0800","msg":"当前程序所在文件位置","pid":"5836","info":["D:\\Lib\\os_Software\\SamWaf\\SamWaf64.exe"]}
{"level":"info","ts":"2024-09-21T10:34:47.625+0800","msg":"user_code:","pid":"5836","info":["e295b599-9a5d-43ce-be38-00138c9b237a"]}
{"level":"info","ts":"2024-09-21T10:34:47.626+0800","msg":"sof_id:","pid":"5836","info":["SamWafCom"]}
{"level":"info","ts":"2024-09-21T10:34:47.626+0800","msg":"执行位置:","pid":"5836","info":["D:\\Lib\\os_Software\\SamWaf\\SamWaf64.exe"]}
{"level":"info","ts":"2024-09-21T10:34:47.626+0800","msg":"初始化系统 版本号：20240920(v1.3.2) 发行版本 windows","pid":"5836","info":null}
{"level":"info","ts":"2024-09-21T10:34:47.626+0800","msg":"OutIp","pid":"5836","info":["139.227.193.44"]}
{"level":"info","ts":"2024-09-21T10:34:47.626+0800","msg":"当前程序所在文件位置","pid":"5836","info":["D:\\Lib\\os_Software\\SamWaf\\SamWaf64.exe"]}
{"level":"info","ts":"2024-09-21T10:34:47.628+0800","msg":"文件备份成功，备份文件路径：","pid":"5836","info":["D:\\Lib\\os_Software\\SamWaf\\data\\backups\\local_backup_20240921103447.db"]}
{"level":"info","ts":"2024-09-21T10:34:47.692+0800","msg":"当前程序所在文件位置","pid":"5836","info":["D:\\Lib\\os_Software\\SamWaf\\SamWaf64.exe"]}
{"level":"info","ts":"2024-09-21T10:34:47.783+0800","msg":"当前程序所在文件位置","pid":"5836","info":["D:\\Lib\\os_Software\\SamWaf\\SamWaf64.exe"]}
{"level":"error","ts":"2024-09-21T10:34:47.803+0800","msg":"load sensitive error","pid":"5836","err":[{}]}
{"level":"info","ts":"2024-09-21T10:34:47.822+0800","msg":"ProcessDequeEngine start","pid":"5836","info":null}
{"level":"info","ts":"2024-09-21T10:34:47.830+0800","msg":"检测是否需要进行分库","pid":"5836","info":null}
{"level":"info","ts":"2024-09-21T10:34:47.837+0800","msg":"当前程序所在文件位置","pid":"5836","info":["D:\\Lib\\os_Software\\SamWaf\\SamWaf64.exe"]}
{"level":"info","ts":"2024-09-21T10:34:47.882+0800","msg":"regInfo","pid":"5836","info":[{}]}

**Comment by samwafgo** [comment]
是双击直接启动的吗？

**Comment by samwafgo** [comment]
这个情况下 ，本地访问：http://127.0.0.1:26666


是否正常显示界面呢？

**Comment by samwafgo** [comment]
已经在samwaf启动成功后显示提示信息，有问题可以再反馈
