### ISSUE TITLE
[Bug] TZ设置时区不管用

### ISSUE THREAD

**Issue by jhsswl** [samwafgo/SamWaf#20]
### 产品版本

202410(v1.3.7-beta.6)

### 版本类型

- [X] 社区版

### 环境信息

rocky 8 linux系统，docker容器运行samwaf是通过命令设置-e TZ=/Asia/Shanghai，容器内部时间依然没有改变，通过映射宿主机时间文件依然不行

### 🐛 缺陷描述

rocky 8 linux系统，docker容器运行samwaf是通过命令设置-e TZ=/Asia/Shanghai，容器内部时间依然没有改变，通过映射宿主机时间文件依然不行

### 期望结果

时间能够改变成本地时间

**Comment by samwafgo** [comment]
感谢反馈，这个等我来验证一下

**Comment by samwafgo** [comment]
确认问题
