### ISSUE TITLE
[Bug] 同一ip不同端口时，在选择框里无法区分

### ISSUE THREAD

**Issue by BnjaLin** [samwafgo/SamWaf#22]
### 产品版本

最新版

### 版本类型

- [ ] 社区版

### 环境信息

前端网页

### 🐛 缺陷描述

![image](https://github.com/user-attachments/assets/8472d3d2-c236-43ff-ae5e-216292e53e72)

### 期望结果

在选择框里可以显示ip+端口，以区分不同的服务

**Comment by samwafgo** [comment]
感谢反馈
