### ISSUE TITLE
似乎无法让80自动跳转到443

### ISSUE THREAD

**Issue by logce** [samwafgo/SamWaf#27]
你好，如题，最新版本，是否有这个功能

**Comment by samwafgo** [comment]
目前没有这个功能，现在的做法是 再创建一个80的站点 然后里面进行跳转https网址，进行跳转

**Comment by samwafgo** [comment]
v1.3.7-beta.11 已支持80跳转443 可以下载体验了。
![jump443](https://github.com/user-attachments/assets/f6b3ec89-deea-4e41-9285-0c0c5d928335)

**Comment by logce** [comment]
可用，👍
