### ISSUE TITLE
[Bug] 前端如果部署有nginx等反向代理的话SamWaf无法获取到真实IP

### ISSUE THREAD

**Issue by tsgdnwxg** [samwafgo/SamWaf#3]
### 产品版本

SamWaf_Windows_x86_64.v1.3.2

### 版本类型

- [X] 社区版

### 环境信息

windows server 2012 r2版本，上级域名管理，通过Nginx转发外部请求到内网服务器，内网服务器通过Nginx转发请求到各个后端服务端口。

### 🐛 缺陷描述

上一级使用反向代理的情况下，获取到的IP地址都是上级反代的IP，无法通过真实客户端IP进行甄别

### 期望结果

获取客户端真实IP，并针对高频IP添加人机验证等

**Comment by samwafgo** [comment]
感谢反馈，下个版本把这个情况处理一下

**Comment by samwafgo** [comment]
下个版本加入
默认识别:**X-Forwarded-For,X-Real-IP**

```

如果有自己的标记头可以在此进行配置,用逗号隔开

菜单路径：系统设置->参数设置

配置说明：获取访客IP头信息（按照顺序）
配置项: gwaf_proxy_header
默认值:X-Forwarded-For,X-Real-IP

```
