### ISSUE TITLE
[Feature] 测试报告的检测率有些低，后续会有提升吗？

### ISSUE THREAD

**Issue by caiqy** [samwafgo/SamWaf#4]
### 产品版本

1.3.2

### 版本类型

- [X] 社区版

### ⭐️ 需求描述

检测率只有28.27%，是什么原因导致的呢？后续会不会加强这块的更新？

**Comment by samwafgo** [comment]
感谢关注。

SamWaf还在持续学习和发展，增加识别率是一项长期且重要的工作目标。
也期待更多朋友参与其中。

**Comment by djy1121** [comment]
> 感谢关注。
> 
> SamWaf还在持续学习和发展，增加识别率是一项长期且重要的工作目标。 也期待更多朋友参与其中。

你好！问一下，samwaf的检测引擎和规则全都是作者自己实现的吗？

**Comment by samwafgo** [comment]
此处有引用三方库的信息：
 https://github.com/samwafgo/SamWaf/blob/main/docs/compile.md#%E9%9B%86%E6%88%90%E7%9A%84%E4%B8%89%E6%96%B9%E5%BA%93
