### ISSUE TITLE
[Feature] 能否支持arm64的cpu架构

### ISSUE THREAD

**Issue by caiqy** [samwafgo/SamWaf#42]
### 产品版本

v1.3.7-beta.20

### 版本类型

- [X] 社区版

### ⭐️ 需求描述

希望能支持arm64，看代码是golang写的，应该是可以直接支持的吧

### 补充信息

可以的话，希望能在dockerhub发布arm64的镜像

**Comment by samwafgo** [comment]
感谢反馈。

因为里面涉及cgo了，所在这个编译应得在arm环境下编译。

arm是否可以想x86一样，Arm可以用vmbox，vmware 虚拟出来一个操作系统呢？

**Comment by caiqy** [comment]
在 x86_64 系统上运行 ARM64 模拟器是可行的，但需要使用适当的软件工具。VMware 本身并不直接提供 ARM64 模拟功能，不过你可以通过其他方式实现 ARM64 的仿真或模拟。以下是一些方法和工具：

1. **QEMU**：
   - QEMU 是一个通用的开源仿真器和虚拟机，可以用于在 x86_64 环境中仿真 ARM64 架构。它通过动态二进制翻译来模拟不同架构的指令集。
   
   - 使用 QEMU 你可以创建一个 ARM64 的虚拟机，配置 ARM64 的系统镜像，并运行 ARM64 应用。

2. **Cross-compilation 和 Emulation**：
   - 除了使用 QEMU 进行完整的系统仿真，你还可以跨平台编译 ARM64 应用程序并在模拟环境中测试。使用工具链如 GCC 或 Clang 的 cross-compiler 可以编译 ARM64 二进制文件。

3. **Docker 和 QEMU**：
   - 如果你需要在容器环境中进行 ARM64 的应用测试，可以结合 Docker 和 QEMU 来实现。在 Docker 中，使用 `qemu-user-static` 可以在 x86_64 主机上运行 ARM64 的 Docker 镜像。

4. **其他仿真平台**：
   - 除了 QEMU 外，有些专业的商业工具也提供跨架构的仿真功能。不过这些通常是面向开发的付费解决方案。

需要注意的是，由于仿真涉及指令集转译和模拟，性能往往会受到影响，通常比直接在原生 ARM64 硬件上运行要慢。如果可能，考虑使用 ARM64 硬件（如 Raspberry Pi 或其他 ARM64 开发板）进行更高效的开发和测试。

**Comment by caiqy** [comment]
好像其他项目是通过github的action来编译不同环境安装包的

**Comment by samwafgo** [comment]
好的 等后面研究一下

**Comment by samwafgo** [comment]
> debian能部署SamWaf吗

应该得看架构 是arm的还是其他类型的

**Comment by caiqy** [comment]
😄作者，这个什么时候能实现呢？能不能给feature排一个todo-list

**Comment by samwafgo** [comment]
> arm64的镜像

1. 编译问题在同步研究，有进展会同步到个各各关联的issue
2. 目前策略是比较相似、集中 、小的需求进行优先处理，其他大块的会穿插研究

**Comment by caiqy** [comment]
> > arm64的镜像
> 
> 1. 编译问题在同步研究，有进展会同步到个各各关联的issue
> 2. 目前策略是比较相似、集中 、小的需求进行优先处理，其他大块的会穿插研究

好的，感谢回复

**Comment by samwafgo** [comment]
@caiqy  可以测试一下了 v1.3.8-beta.12 ，docker也同步上去

**Comment by caiqy** [comment]
@samwafgo 感谢，已经运行起来了，遇到问题再给你反馈

**Comment by WyInnovate** [comment]
> @samwafgo 感谢，已经运行起来了，遇到问题再给你反馈

arm正常吗?我这里本地反代本地都没反应,在x86机器上没问题
