### ISSUE TITLE
[Bug] 响应报文为什么记录不了

### ISSUE THREAD

**Issue by aaq1adqwe** [samwafgo/SamWaf#44]
### 产品版本

最新版

### 版本类型

- [X] 社区版

### 环境信息

[Bug] 响应报文为什么记录不了

### 🐛 缺陷描述

[Bug] 响应报文为什么记录不了，PUT、和一些POST请求，都没有响应报文，是设置问题么

**Comment by samwafgo** [comment]
系统设置->参数设置看下下面两个参数：

```
record_resp   是否记录相应报文 1为记录
record_max_res_body_length 如果上面为1 最大响应报文的字节大小
```

**Comment by aaq1adqwe** [comment]
设置了，还是会记录不了😂，只有拦截了的会有，没有拦截的是不记录么

**Comment by samwafgo** [comment]
关闭了 有问题再提单
