### ISSUE TITLE
[Feature] 能刷到路由器里面吗，直接作为前置管控

### ISSUE THREAD

**Issue by aspnmy** [samwafgo/SamWaf#5]
### 产品版本

main

### 版本类型

- [X] 社区版

### ⭐️ 需求描述

想尝试刷到开源路由器里，作为接入端前置管控

**Comment by samwafgo** [comment]
开源路由器一般是什么操作系统呢？本地没有设备能模拟测试吗？

**Comment by uouuou** [comment]
一般openwrt的路由都没有问题，可以安装进去，自己编译一下arm版本就好了，x86的直接用即可

**Comment by wuxiuxiu521** [comment]
我的路由器是AX1800Pro 处理器是Arm64v8a A53四核 运行了openwrt 能否兼容arm版本 有无讨论群

**Comment by aspnmy** [comment]
> 我的路由器是AX1800Pro 处理器是Arm64v8a A53四核 运行了openwrt 能否兼容arm版本 有无讨论群

本地设备刷过了 可以跑 官方不知道有没有群

**Comment by aspnmy** [comment]
飞机上我们有综合讨论群

**Comment by wuxiuxiu521** [comment]
方便提供一下tg群号么

**Comment by aspnmy** [comment]
> 方便提供一下tg群号么
新群组，综合讨论，不局限这个项目
https://t.me/+BqvlH6BDOWE3NjQ1
