### ISSUE TITLE
[Feature] ipv6支持

### ISSUE THREAD

**Issue by Omoinemie** [samwafgo/SamWaf#50]
### 产品版本

v1.3.8-beta.2

### 版本类型

- [X] 社区版

### ⭐️ 需求描述

服务器有ipv6，用samwaf无法正确代理，浏览器访问代理的网站解析出来是ipv6地址，但samwaf并不能6to4或者6to6

**Comment by samwafgo** [comment]
ipv6的等后面统一处理一下

**Comment by 13653216371** [comment]
+1，期待支持6to6，或者6to4

**Comment by samwafgo** [comment]
v1.3.8-beta.18，支持ipv6 归属地国家的识别，可以测试了
