### ISSUE TITLE
ip白名单功能

### ISSUE THREAD

**Issue by MadeLuckyBoy** [samwafgo/SamWaf#52]
### 产品版本

1.3.7

### 版本类型

- [X] 社区版

### ⭐️ 需求描述

我新建一个网站想实现只允许ip白名单内的IP进行访问，其他ip禁止访问的场景
在已设置ip白名单的情况下，能否可设置封禁所有ip访问，只允许白名单内的IP进行访问

**Comment by samwafgo** [comment]
感谢反馈

**Comment by samwafgo** [comment]
等v1.3.8-beta.5版本 

进行如下配置：
```
白名单添加授信IP：如127.0.0.1
黑名单添加IP段:0.0.0.0/0 ，
表示除了白名单IP以外的IP，所有IP都不允许访问
```
