### ISSUE TITLE
[Feature] 隐藏响应标头中的samwaf信息

### ISSUE THREAD

**Issue by Omoinemie** [samwafgo/SamWaf#57]
### 产品版本

1.3.7

### 版本类型

- [X] 社区版

### ⭐️ 需求描述

预防基于产品缺陷的定性攻击
![image](https://github.com/user-attachments/assets/e7ef08b0-f3a7-4bcf-bba5-afdbf8e75fc5)

**Comment by samwafgo** [comment]
感谢反馈
