### ISSUE TITLE
[Feature] 希望能单独配置证书，在网站防护页支持选择已有SSL配置，不用每次添加都输入一遍公钥私钥

### ISSUE THREAD

**Issue by lhchong** [samwafgo/SamWaf#6]
### 产品版本

~

### 版本类型

- [ ] 社区版

### ⭐️ 需求描述

希望能单独配置证书，在网站防护页支持选择已有SSL配置，不用每次添加都输入一遍公钥私钥

### 补充信息
![image](https://github.com/user-attachments/assets/a839f68d-3738-4020-bdc5-eabe068a6544)
![image](https://github.com/user-attachments/assets/3b34c2f7-2e15-4668-9775-2ce6a4db8aaa)

_No response_

**Comment by samwafgo** [comment]
感谢反馈

使用的场景是：多个域名使用的同一个证书，泛域名那种情况吗？

**Comment by friesen365** [comment]
> 感谢反馈
> 
> 使用的场景是：多个域名使用的同一个证书，泛域名那种情况吗？

一般个人用户不会管理太多域名，手里只有一两个域名通过配置泛域名的方式来实现多服务访问（使用相同的泛域名证书）。
单独设置一个证书管理模块，在进行绑定时直接引用证书使用体验会更好。而且后期证书到期需要更新也更高效。

**Comment by samwafgo** [comment]
后面紧接着的版本会把这个处理一下
