### ISSUE TITLE
[Bug] URL白/黑名单文本错误

### ISSUE THREAD

**Issue by nickdlkk** [samwafgo/SamWaf#66]
### 产品版本

20241120(v1.3.8-beta.14) 

### 版本类型

- [X] 社区版

### 环境信息

docker安装 20241120(v1.3.8-beta.14) 

### 🐛 缺陷描述

![图片](https://github.com/user-attachments/assets/957d40b9-3d11-4650-b414-95a35c136b42)
中文文本错误

### 期望结果

看截图文本应该是URL

### 补充信息
![图片](https://github.com/user-attachments/assets/49979441-faf8-4425-a8d8-d1dcc61d3c90)
英文是正常的

_No response_

**Comment by samwafgo** [comment]
感谢反馈
