### ISSUE TITLE
[Bug] 内网IP归属地为"0"

### ISSUE THREAD

**Issue by nickdlkk** [samwafgo/SamWaf#68]
### 产品版本

20241120(v1.3.8-beta.14) 

### 版本类型

- [ ] 社区版

### 环境信息

Docker部署

### 🐛 缺陷描述

![图片](https://github.com/user-attachments/assets/b1af8a90-f4a7-4e3a-97fc-31044e10f469)
![图片](https://github.com/user-attachments/assets/19c15aa1-ab0d-4a9a-8e02-0b083e6e7a05)

内网IP的归属地是0 

### 期望结果

可以换成文本"内网"或者自定义IP映射

**Comment by samwafgo** [comment]
后面改成内网，这样比较通用一些
