### ISSUE TITLE
[Bug] 使用docker部署，映射80为非80端口后，在网页防护处填写实际外网访问端口无法访问

### ISSUE THREAD

**Issue by coracoo** [samwafgo/SamWaf#7]
### 产品版本

1.3.3

### 版本类型

- [X] 社区版

### 环境信息

docker部署
![QQ_1727967829779](https://github.com/user-attachments/assets/c605b2a9-b930-4097-aced-95ce53131776)

### 🐛 缺陷描述

在NAS中使用docker部署该项目，将80端口映射为40080。

在网站防护处填写访问地址为NAS IP + 40080，无法访问系统，无报错，无日志。

![QQ_1727967782166](https://github.com/user-attachments/assets/c185baea-7282-477b-a64b-e5b5546457d7)

因此考虑容器只接受80端口，所以把网站防护改为NAS IP + 80端口，可以访问，但是形成403报错。

![QQ_1727967628448](https://github.com/user-attachments/assets/1ae5ca69-9e68-4b76-80de-81bbf482c639)

![QQ_1727967651420](https://github.com/user-attachments/assets/2e98654e-a259-4a27-8c84-cbe284e9d6e7)

**Comment by samwafgo** [comment]
提示无法访问时候，SamWaf和后面网站是在同一个容器里面 还是不同容器里面呢？

**Comment by coracoo** [comment]
> 提示无法访问时候，SamWaf和后面网站是在同一个容器里面 还是不同容器里面呢？

samwaf部署在NAS设备A上，为bridge模式，映射了端口，NAS A的地址即192.168.0.129。

后端网站是局域网下的另外一台设备上的服务，即192.168.0.125:5233

**Comment by samwafgo** [comment]
应该和该issues #9 情况一样 ，等修正一下看下情况

**Comment by coracoo** [comment]
>  应该和该issues #9 情况一样 ，等修正一下看下情况

看了一下的确是同一个情况，阉割匹配的话，导致非80，443无法使用了，或者建议docker给个环境变量参数，可以自定义透出端口，感谢

**Comment by samwafgo** [comment]
v1.3.5 发布了，方便时候可以试试了

**Comment by coracoo** [comment]
> v1.3.5 发布了，方便时候可以试试了

 docker内依旧是v1.3.3版本

**Comment by samwafgo** [comment]
> > v1.3.5 发布了，方便时候可以试试了
> 
> docker内依旧是v1.3.3版本

刚把最新版本v1.3.5的docker进行推送上去了

**Comment by Dlian-Zero** [comment]
设备80、443端口被其他应用占用，请问映射其他端口可以吗

**Comment by samwafgo** [comment]
> 设备80、443端口被其他应用占用，请问映射其他端口可以吗

看下这个架构图 https://doc.samwaf.com/guide/Host.html   ，有问题再补充

**Comment by coracoo** [comment]
测试正常了，可以关闭。感谢。
