### ISSUE TITLE
[Bug] 新增网站时，设置的后端域名没有达到预期作用

### ISSUE THREAD

**Issue by surenkid** [samwafgo/SamWaf#78]
### 产品版本

v1.3.7

### 版本类型

- [X] 社区版

### 环境信息

waf所在服务器为s1，后端服务所在服务器为s2（绑定ddsn.back-end.com动态域名）

后端服务器s2上部署了nginx，nginx配置中为服务绑定了域名 www.back-end.com 

waf新增网站配置如图：

![image](https://github.com/user-attachments/assets/9df22799-41a9-406e-b291-86d7b0e1b225)

### 🐛 缺陷描述

通过访问http://www.front-end.com ，虽然能正常访问到后端服务器s2上的 80 端口，但是s2上的nginx无法识别到后端域名( www.back-end.com )，导致显示为default页。

可能的原因是，没有传递正确的`proxy_set_header Host $host;`到后端服务器。这里的$host应该为后端域名 www.back-end.com 而不是 www.front-end.com  

### 期望结果

通过访问 http://www.front-end.com ，访问到后端服务器s2上的 www.back-end.com 服务

**Comment by samwafgo** [comment]
感谢反馈

**Comment by samwafgo** [comment]
[v1.3.9-beta.1](https://github.com/samwafgo/SamWaf/releases/tag/v1.3.9-beta.1)  可以试试了

**Comment by WyInnovate** [comment]
> [v1.3.9-beta.1](https://github.com/samwafgo/SamWaf/releases/tag/v1.3.9-beta.1) 可以试试了

大佬，我感觉是此次更新是破坏性更新，今天早上我的计划任务自动更新到了v1.3.9-beta.1，然后后端的1panel就提示：网站不存在，请检查域名，看来是需要重新修改后端域名才能正常，等我回家看看
另外我看了下大佬的镜像samwaf/samwaf标签打的是latest，建议beta就打beta标签

**Comment by samwafgo** [comment]
非常感谢 @WyInnovate 完备的测试和建议 。

后面版本发布的时候研究一下发版策略。

**Comment by samwafgo** [comment]
@WyInnovate 另外计划任务的是怎么配置的呢？

**Comment by WyInnovate** [comment]
> @WyInnovate 另外计划任务的是怎么配置的呢？

我是在1panel里设置了一个计划任务，使用watchtower来检查当前运行的容器是否有更新，平时也可以直接运行watchtower容器来检查是否有更新，计划任务如图所示
![image](https://github.com/user-attachments/assets/5aea9ca0-9989-4bfd-82de-af614df98e62)

另外贴一下运行watchtower容器的命令
```
docker run --rm --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --run-once
```

**Comment by surenkid** [comment]
谢谢，我今天测试一下 @samwafgo 

另，计划任务自动更新，我自己的方案是：
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --run-once samwaf-surenkid
```
其中`samwaf-surenkid`为容器名称

**Comment by samwafgo** [comment]
这个功能后面马上要加一个开关，如果要识别后端的域名 就打开，否则就关闭 。需要注意一下。

**Comment by samwafgo** [comment]
watchtower 这个监控的是latest 标识 还是 按照更新的时间呢？

**Comment by WyInnovate** [comment]
> watchtower 这个监控的是latest 标识 还是 按照更新的时间呢？

是镜像的标签，镜像是什么标签就去找这个标签，所以我才说beta打beta的标签

**Comment by samwafgo** [comment]
> > watchtower 这个监控的是latest 标识 还是 按照更新的时间呢？
> 
> 是镜像的标签，镜像是什么标签就去找这个标签，所以我才说beta打beta的标签

也就是之前是拉取的latest 标签是吧 ？

**Comment by WyInnovate** [comment]
> > > watchtower 这个监控的是latest 标识 还是 按照更新的时间呢？
> > 
> > 
> > 是镜像的标签，镜像是什么标签就去找这个标签，所以我才说beta打beta的标签
> 
> 也就是之前是拉取的latest 标签是吧 ？

是的

**Comment by samwafgo** [comment]
> > > > watchtower 这个监控的是latest 标识 还是 按照更新的时间呢？
> > > 
> > > 
> > > 是镜像的标签，镜像是什么标签就去找这个标签，所以我才说beta打beta的标签
> > 
> > 
> > 也就是之前是拉取的latest 标签是吧 ？
> 
> 是的

ok

**Comment by samwafgo** [comment]
> [surenkid](/surenkid)

@surenkid  注意一个情况， 一会发布得**v1.3.9-beta.2** 版本里面会默认关闭，自行打开一下就可以适配了

**Comment by surenkid** [comment]
> > [surenkid](/surenkid)
> 
> @surenkid 注意一个情况， 一会发布得**v1.3.9-beta.2** 版本里面会默认关闭，自行打开一下就可以适配了

已经了解，感谢提醒。
