### ISSUE TITLE
[Feature] 使用源码跑起来的项目，新建防护不起作用

### ISSUE THREAD

**Issue by AntonyCheng** [samwafgo/SamWaf#83]
### 产品版本

1.3.8

### 版本类型

- [X] 社区版

### ⭐️ 需求描述

![image](https://github.com/user-attachments/assets/768a3ea3-cce9-4f70-abe3-ee2f98f3f541)

**Comment by AntonyCheng** [comment]
这个是在局域网环境下的两台机器，我怀疑是我配置错误了，第一次接触这个WAF系统，有点不太熟悉

**Comment by AntonyCheng** [comment]
这个内网网站是直接由IDEA启动的一个SpringBoot前后端分离项目

**Comment by samwafgo** [comment]
前后端分离的项目，最好是把他们先整合在一个ip能访问。

可以考虑在这样的架构：
samwaf ->nginx （做好前后端的处理）->后面的 前后端程序。

**Comment by AntonyCheng** [comment]
我能理解成上面那个图片中第二个端口尽可能改为80或者443么，我昨天后面试了一下本地的80端口是能够监控到的

**Comment by samwafgo** [comment]
> 我能理解成上面那个图片中第二个端口尽可能改为80或者443么，我昨天后面试了一下本地的80端口是能够监控到的

这倒不是必须的，如果单个设置的话 就只能防护 后端或者前端。

**Comment by AntonyCheng** [comment]
您好 我把目前的情况先说一下，我现在使用Nginx代理了：

![58fcc81a4820bd80de3a23a19e874d7](https://github.com/user-attachments/assets/cc7525d4-434e-4c07-891a-a774502b63cc)

正常也能访问成功：

![image](https://github.com/user-attachments/assets/9c3f8785-bf4a-49f6-86ef-8c4e5fda0433)

然后我在咱们平台上这么配置就显示端口占用，我看官网文档上面写如果占用就修改非80或者443端口，但是我此时用的是81端口，这有什么解决方案么？

![dac10398cfd95f18ee87673bb07a749](https://github.com/user-attachments/assets/8c13fe88-8354-402a-b3de-e52a26a67f33)

**Comment by samwafgo** [comment]
防护的那条数据 配置一下 后端的端口 80

**Comment by samwafgo** [comment]
提示被占用 查查是哪个程序占用了 80端口

**Comment by AntonyCheng** [comment]
> 您好 我把目前的情况先说一下，我现在使用Nginx代理了：
> 
> ![58fcc81a4820bd80de3a23a19e874d7](https://private-user-images.githubusercontent.com/88792183/393065482-cc7525d4-434e-4c07-891a-a774502b63cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTE4NjMsIm5iZiI6MTczMzQ1MTU2MywicGF0aCI6Ii84ODc5MjE4My8zOTMwNjU0ODItY2M3NTI1ZDQtNDM0ZS00YzA3LTg5MWEtYTc3NDUwMmI2M2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDAyMTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYTUzNWE2YTU3NTMzYzFhZDA4NGJhZjE5ZTA3ODUzNDdjNWE0N2FkNGQ2NzBhNTYzY2U5MzgwY2NmZmYzODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GREymGq5vuCJ4t8ytUrh__UAuSO0eSu8WQApcrFXQ3E)
> 
> 正常也能访问成功：
> 
> ![image](https://private-user-images.githubusercontent.com/88792183/393065588-9c3f8785-bf4a-49f6-86ef-8c4e5fda0433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTE4NjMsIm5iZiI6MTczMzQ1MTU2MywicGF0aCI6Ii84ODc5MjE4My8zOTMwNjU1ODgtOWMzZjg3ODUtYmY0YS00OWY2LTg2ZWYtOGM0ZTVmZGEwNDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDAyMTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5Y2Y1ZWIxMjgxMjMzZDY3YTdkMjE2ODJhNzdkODgzYTZhOWJkZTU2Y2JkZmVhMjhjNzhiNTE4MjE3NTk1NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4yoX_XVEIEoQp3NCjuNtpwNtzezOnLH-5X2NrSfSxlk)
> 
> 然后我在咱们平台上这么配置就显示端口占用，我看官网文档上面写如果占用就修改非80或者443端口，但是我此时用的是81端口，这有什么解决方案么？
> 
> ![dac10398cfd95f18ee87673bb07a749](https://private-user-images.githubusercontent.com/88792183/393066146-8c13fe88-8354-402a-b3de-e52a26a67f33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTE4NjMsIm5iZiI6MTczMzQ1MTU2MywicGF0aCI6Ii84ODc5MjE4My8zOTMwNjYxNDYtOGMxM2ZlODgtODM1NC00MDJhLWIzZGUtZTUyYTI2YTY3ZjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDAyMTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZDk1NDU0MzUxYzVkODcyNGQ2ODgyOTc4YTA0NGEwZDQzYzc5NGMxNTBmOGRlYzY2ZjZlMmMzYTI4OWM5ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZpWeb0Ia5BHEKRIpCHNZY_zsEHubcwYqGtlg9fQKwss)

这个地方显示的是81端口被占用，81端口是Nginx配置的前端页面端口，应该是Nginx占用了，咱们这个后端端口指的是比如SpringBoot后端程序的端口么

**Comment by samwafgo** [comment]
不限定，后端、前端都算。被waf防护的 这里都统一叫 后端了

**Comment by AntonyCheng** [comment]
我明白了，这个项目真是解决了我一个大问题，谢谢你耐心的指导😊
