### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by zsinba** [samwafgo/SamWaf#9]
### 产品版本

Git Latest Code

### 版本类型

- [X] 社区版

### ⭐️ 需求描述

在配置域名和端口时，只有域名+端口全部匹配的时候，才会走到 waf，这样似乎并不合适。

比如：
*.abc.com
8081
到
192.168.1.222
80

此时外层还有 nginx，或者 cdn 之类的， 外层访问是  *.abc.com， waf 无法命中。

期望：只检测域名，不要检测端口，加大 waf 命中的概率。

**Comment by samwafgo** [comment]
也就是域名上配置的是泛域名，然后都解析到nginx这台机器，然后 在到samwaf 是这个样子吗？

**Comment by zsinba** [comment]
不是泛解析的事情。
当前 samwaf 使用的时候，要Domain+Port 匹配上配置的内容，才会走到对应的源站了。

期望的是： 仅匹配 Domain，不匹配 Port。

原因如下：
例如 a.bc.com 这样的域名绑定过来。
无论 使用哪个端口进入到 waf 的，都处理它。

当前不能处理的原因：
a.bc.com 81 ----- 192.168.1.222 80
此时一定要 http://a.bc.com:81才被 waf 接受。
期望的是： http://a.bc.com 就接受。

**Comment by friesen365** [comment]
> 当前不能处理的原因：
> a.bc.com 81 ----- 192.168.1.222 80
> 此时一定要 http://a.bc.com:81才被 waf 接受。
> 期望的是： http://a.bc.com 就接受。
——————

你的需求是否为全端口绑定？
即把a.bc.com的1-65535全部端口都绑定到192.168.1.222:80

从而实现无论访问域名哪个端口都可以访问192.168.1.222:80

**Comment by zsinba** [comment]
不是。 
绑定的时候，就使用 81 来绑定
waf:
a.bc.com 81 （IP 为：10.1.1.10）
源站：
192.168.1.222 80

再外层有个 Nginx
使用 a.bc.com （80 和 443）---指向 waf  （10.1.1.10：81）----  源站192.168.1.222 80

此时公网通过 a.bc.com 访问，会停留在 waf 层， waf 不会往源站转发。
期望他向源站转发。

**Comment by friesen365** [comment]
> 不是。 
> 绑定的时候，就使用 81 来绑定
> waf:
> a.bc.com 81 （IP 为：10.1.1.10）
> 源站：
> 192.168.1.222 80
> 
> 再外层有个 Nginx
> 使用 a.bc.com （80 和 443）---指向 waf  （10.1.1.10：81）----  源站192.168.1.222 80
> 
> 此时公网通过 a.bc.com 访问，会停留在 waf 层， waf 不会往源站转发。
> 期望他向源站转发。
> 
> 

明白了，我还没部署samwaf，刚用雷池测试是正常的。发一下你nginx和waf的配置？

**Comment by zsinba** [comment]
我的外层 nginx，是腾讯 cdn。
cdn 转发到内网是 waf 上。 
是的， 雷池的确正常的。

**Comment by samwafgo** [comment]
明白了

**Comment by samwafgo** [comment]
主机配置里面新增一个开关：来源严格端口 默认是开启，如果关闭后 适合外层nginx,cdn情况

**Comment by samwafgo** [comment]
@zsinba v1.3.5 发布了，方便时候可以试试了
